import type { Metadata } from "next";
import Link from "next/link";
import Guide from "@/components/world/Guide";
import { WorldPage } from "@/components/world/WorldShell";
import { SOURCE_URL } from "@/lib/marketing-content";
export const metadata: Metadata = { title: "Get started — M9R docs", description: "Install M9R, review local setup permissions, connect agents, and troubleshoot." };
export default function GetStarted() {
  return <WorldPage label="DOCS / GET STARTED" title="Make the connection." intro="A practical guide, not a magic trick. Hosted connection and native local setup are separate paths; preview commands are labeled throughout.">
    <section id="windows-engine"><h2>Standalone Windows setup</h2><p>The self-contained Windows engine is distributed as a versioned GitHub release when one is published. It does not require Node.js or npm. Download the ZIP and adjacent SHA-256 file from the same <a href="https://github.com/ayaanali-ai/M9R/releases?q=m9r-engine">M9R engine releases ↗</a>; verify the checksum before extracting, then review <code>install-m9r.ps1</code> and <code>INSTALLATION.txt</code> before running the installer. The executables are currently unsigned: a checksum verifies that the file matches the downloaded sidecar, but is not a publisher signature.</p><p>The installer shows the engine’s exact proposed changes before asking for approval. It installs per-user (no administrator access), backs up files before changing them, and can reverse its managed setup. Do not use a command that pipes downloaded code directly into PowerShell.</p><p>First-run setup adds M9R-managed instructions and hooks to supported local agent configuration and installs the engine and hook helper under <code>%USERPROFILE%\.m9r\bin</code>. The local engine watches supported local session files for status and explicit agent mentions; this local setup does not upload those files or require an M9R account. Hosted connections are separate. Codex may show its own <code>/hooks</code> trust screen, which remains optional and under your control.</p><p>After setup, start a new supported agent session. To review or reverse the managed local setup, run <code>m9r-engine.exe uninstall</code> from <code>%USERPROFILE%\.m9r\bin</code>, or use the package’s <code>install-m9r.ps1 -Uninstall</code> wrapper.</p><p><strong>Release status:</strong> no public standalone-engine release is linked from this page yet. Until one is published, use the CLI installation path below.</p></section>
    <section><h2>What you need</h2><p>Node.js, a terminal, and the provider apps you intend to connect. The CLI package declares Node 18 or newer; use a currently supported Node release. Keep your provider accounts signed in.</p><p><a href={`${SOURCE_URL}/tree/main/cli`}>CLI source and requirements ↗</a> · <Link href="/auth?mode=signup">Create an account</Link> for hosted connections.</p></section>
    <Guide />
    <section id="troubleshooting"><h2>If something isn’t connecting.</h2>
      <details><summary>Command not found</summary><p>Use <code>m9r-cli</code>, not <code>m9r</code>. Check that Node and npm are installed and npm’s global executable directory is on your PATH. Open a new terminal after installation.</p></details>
      <details><summary>Unknown setup or uninstall command</summary><p>The standalone Windows engine and npm CLI are distinct distributions. In the standalone build, use <code>m9r-engine.exe setup</code> or <code>m9r-engine.exe uninstall</code>. In the npm package, use the commands shown by <code>m9r-cli --help</code>. Do not assume a command exists in a distribution until that version documents it.</p></details>
      <details><summary>An agent is missing</summary><p>Check that its app is installed and logged in, then run the diagnostic command supported by your installed distribution. Local setup can install supported hooks and instructions, but does not automatically make every provider reachable or authenticate an agent with M9R.</p></details>
      <details><summary>Hooks or tools aren’t loaded</summary><p>Start a new Claude Code session after setup. Where Codex hooks are separately installed, review them in <code>/hooks</code>. After configuring Claude Desktop tools, restart Desktop.</p></details>
      <details><summary>A task was queued but no reply arrived</summary><p>A queue entry is not a delivery receipt. Confirm the recipient has an installed integration and active session. Local preview tasks appear on the next prompt, not as guaranteed background execution.</p></details>
      <details><summary>I want to undo this</summary><p>The standalone Windows package uses <code>m9r-engine.exe uninstall</code>; the npm distribution uses the uninstall command it documents. Hosted connections are separate. Uninstall restores managed configuration changes and is not the same as purging local M9R data.</p></details>
    </section>
  </WorldPage>;
}
