/**
 * Generates the three provider-side artifacts `m9r connect`/bootstrap writes
 * so a locally-launched Claude Code, Codex, or OpenCode session gets
 * captured into `.oathlock/capture/pending.jsonl` (see
 * cross-agent-capture-core.ts for the drain side). All three functions are
 * pure string/JSON transforms -- no IO -- so the merge logic (never clobber
 * a user's existing hooks/plugins) is fully unit-testable.
 *
 * Deliberately conservative on two open questions, flagged rather than
 * guessed past:
 *  - Codex's exact `.codex/hooks.json` schema was confirmed to exist (event
 *    name `SessionEnd`, a `hooks.json`/`config.toml` file, a `/hooks` trust
 *    review) but this repo has no real Codex install to test the merge
 *    shape live against -- it mirrors Claude Code's documented shape
 *    (the two providers' SessionEnd payloads are field-identical per the
 *    research this was built from), without a `matcher` field, since that
 *    field's exact semantics for Codex weren't independently confirmed.
 *  - OpenCode's plugin uses only the one API confirmed by reading its own
 *    source (`client.session.messages({ sessionID })`); it does not also
 *    fetch session metadata via any unconfirmed method.
 */

export const CAPTURE_HOOK_RELATIVE_PATH = ".oathlock/bin/m9r-capture.mjs";
const HOOK_MARKER = "m9r-capture.mjs";

/**
 * The actual SessionEnd hook script, written into every repo that connects
 * Claude Code or Codex. Deliberately does almost nothing: read stdin JSON,
 * append one line to the spool, exit -- both providers give this well under
 * two seconds (Codex hard-caps at 3s) and treat the hook as advisory, so
 * anything slower than "append and exit" risks either losing the write
 * entirely or, worse, visibly delaying the human's actual exit from their
 * own session. No dependencies beyond node:fs/node:path -- this must run
 * with a bare `node`, not through this repo's own alias/tsx pipeline, since
 * it executes inside a project that may not even be this one.
 */
export const CAPTURE_HOOK_SCRIPT_SOURCE = `#!/usr/bin/env node
// Generated by \`m9r connect\` -- appends this SessionEnd event to
// .oathlock/capture/pending.jsonl for M9R's resident to drain later.
// Deliberately minimal: no dependencies, no network, one append, exit.
// Never throws into the caller -- Claude Code/Codex treat this hook as
// advisory and non-blocking, but a stack trace on stderr would still be
// a needless surprise in someone's terminal on session exit.
import { appendFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";

const provider = process.argv[2] === "codex" ? "codex" : "claude-code";

function readStdin() {
  return new Promise((resolve) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => { data += chunk; });
    process.stdin.on("end", () => resolve(data));
    process.stdin.on("error", () => resolve(data));
    // Providers that never write to stdin for this event must not hang the hook forever.
    setTimeout(() => resolve(data), 1500).unref();
  });
}

async function main() {
  const raw = await readStdin();
  let payload = {};
  try {
    payload = JSON.parse(raw || "{}");
  } catch {
    return; // malformed input -- nothing safe to record, exit quietly
  }
  const sessionId = payload.session_id;
  const transcriptPath = payload.transcript_path;
  if (!sessionId || !transcriptPath) return;

  const cwd = payload.cwd || process.cwd();
  const job = {
    provider,
    sessionId,
    transcriptPath,
    cwd,
    reason: payload.reason || "other",
    capturedAtIso: new Date().toISOString(),
  };
  const projectRoot = process.env.CLAUDE_PROJECT_DIR || cwd;
  const spoolPath = join(projectRoot, ".oathlock", "capture", "pending.jsonl");
  try {
    await mkdir(dirname(spoolPath), { recursive: true });
    await appendFile(spoolPath, JSON.stringify(job) + "\\n", "utf8");
  } catch {
    /* best-effort -- a failed write here just means this one session isn't captured */
  }
}

main().catch(() => {});
`;

function isRecord(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === "object" && !Array.isArray(value);
}

function parseJsonObject(text: string | null): Record<string, unknown> {
  if (!text) return {};
  try {
    const parsed = JSON.parse(text) as unknown;
    return isRecord(parsed) ? parsed : {};
  } catch {
    return {};
  }
}

/**
 * Merges an M9R SessionEnd hook entry into a Claude-Code-shaped settings
 * file (used for both `.claude/settings.local.json` and, mirrored, for
 * Codex's `.codex/hooks.json`). Additive and idempotent: existing
 * `hooks.SessionEnd` groups are preserved untouched; a group whose command
 * already references our own script is left alone rather than duplicated.
 */
function mergeSessionEndHook(
  existingJsonText: string | null,
  hookCommand: string,
  timeoutSeconds: number,
): { content: string; changed: boolean } {
  const root = parseJsonObject(existingJsonText);
  const hooks = isRecord(root.hooks) ? { ...root.hooks } : {};
  const sessionEndGroups = Array.isArray(hooks.SessionEnd) ? [...(hooks.SessionEnd as unknown[])] : [];

  const alreadyPresent = sessionEndGroups.some((group) => {
    if (!isRecord(group) || !Array.isArray(group.hooks)) return false;
    return group.hooks.some((h) => isRecord(h) && typeof h.command === "string" && h.command.includes(HOOK_MARKER));
  });
  if (alreadyPresent) {
    return { content: JSON.stringify(root, null, 2) + "\n", changed: false };
  }

  sessionEndGroups.push({
    hooks: [{ type: "command", command: hookCommand, timeout: timeoutSeconds }],
  });
  hooks.SessionEnd = sessionEndGroups;
  const merged = { ...root, hooks };
  return { content: JSON.stringify(merged, null, 2) + "\n", changed: true };
}

/**
 * `.claude/settings.local.json` — deliberately the gitignored local file,
 * not the committed `.claude/settings.json`. A hook written to the committed
 * file would silently run for every teammate who clones the repo, before
 * they've even seen a trust prompt (project hooks run pre-trust per Claude
 * Code's own permissions docs). Writing to the local file instead makes
 * `m9r connect` itself the per-developer consent, not a repo-wide grant.
 */
export function mergeClaudeCodeLocalSettings(existingJsonText: string | null): { content: string; changed: boolean } {
  return mergeSessionEndHook(
    existingJsonText,
    `node "\${CLAUDE_PROJECT_DIR}/${CAPTURE_HOOK_RELATIVE_PATH}" claude-code`,
    5,
  );
}

/**
 * `.codex/hooks.json` — project-local, real per Codex's own lifecycle-hooks
 * docs. Codex additionally requires an explicit `/hooks` trust review inside
 * the product before a non-managed hook actually runs (a stronger default
 * posture than Claude Code's) -- `m9r connect`'s own output tells the human
 * to do that, this function only writes the definition for them to review.
 */
export function mergeCodexHooks(existingJsonText: string | null): { content: string; changed: boolean } {
  return mergeSessionEndHook(existingJsonText, `node .oathlock/bin/m9r-capture.mjs codex`, 3);
}

/**
 * `.opencode/plugins/m9r-memory.js` — a plain, dependency-free plugin file
 * (OpenCode's own docs ship dependency-free plugin examples the same way).
 * Subscribes to the generic `event` hook rather than a named `session.idle`
 * hook, and handles both `session.idle` (the event OpenCode's own source
 * marks deprecated) and its replacement `session.status` with
 * `status.type === "idle"`, deduped per session id, since which one a given
 * OpenCode version emits isn't something `connect` can detect at write time.
 * Unlike the two hook-based providers, this isn't time-boxed the same way,
 * so it does the transcript fetch itself and spools the finished JSON --
 * the drainer never needs to reach back into a live OpenCode server.
 */
export function buildOpenCodeMemoryPlugin(): string {
  return `// Generated by \`m9r connect\` -- captures this repo's OpenCode sessions into
// M9R's shared memory (.oathlock/capture/pending.jsonl, drained into
// .oathlock/memory/local/opencode/<session-id>.md). Safe to delete; a
// missing plugin just means this repo's OpenCode sessions aren't captured.
//
// Only one OpenCode API is used here (client.session.messages), the one
// this generator's own tests confirmed against OpenCode's real source. If a
// future OpenCode version changes that shape, this plugin fails closed
// (logs to app.log, never throws into the host process) rather than
// spooling malformed data.
import { appendFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";

const seen = new Set();

export const M9rMemoryPlugin = async ({ client, directory, project }) => {
  async function captureIdleSession(sessionID) {
    if (!sessionID || seen.has(sessionID)) return;
    seen.add(sessionID);
    try {
      const result = await client.session.messages({ sessionID });
      const messages = Array.isArray(result?.data) ? result.data : Array.isArray(result) ? result : [];
      const root = directory || project?.worktree || process.cwd();
      const spoolPath = join(root, ".oathlock", "capture", "pending.jsonl");
      const job = {
        provider: "opencode",
        sessionId: sessionID,
        cwd: root,
        capturedAtIso: new Date().toISOString(),
        export: { messages },
      };
      await mkdir(dirname(spoolPath), { recursive: true });
      await appendFile(spoolPath, JSON.stringify(job) + "\\n", "utf8");
    } catch (error) {
      try {
        await client.app.log({ service: "m9r-memory", level: "error", message: String(error?.message || error) });
      } catch {
        /* logging is best-effort; never let capture failures surface to the user */
      }
    }
  }

  return {
    event: async ({ event }) => {
      if (event?.type === "session.idle" && event.properties?.sessionID) {
        await captureIdleSession(event.properties.sessionID);
      } else if (event?.type === "session.status" && event.properties?.info?.status?.type === "idle") {
        await captureIdleSession(event.properties.info.id);
      }
    },
  };
};
`;
}
