/**
 * Generates the three provider-side artifacts `m9r connect`/bootstrap writes
 * so a locally-launched Claude Code, Codex, or OpenCode session gets
 * captured into `.oathlock/capture/pending.jsonl` (see
 * cross-agent-capture-core.ts for the drain side). All three functions are
 * pure string/JSON transforms -- no IO -- so the merge logic (never clobber
 * a user's existing hooks/plugins) is fully unit-testable.
 *
 * Deliberately conservative on two open questions, flagged rather than
 * guessed past:
 *  - Codex's exact `.codex/hooks.json` schema was confirmed to exist (event
 *    name `SessionEnd`, a `hooks.json`/`config.toml` file, a `/hooks` trust
 *    review) but this repo has no real Codex install to test the merge
 *    shape live against -- it mirrors Claude Code's documented shape
 *    (the two providers' SessionEnd payloads are field-identical per the
 *    research this was built from), without a `matcher` field, since that
 *    field's exact semantics for Codex weren't independently confirmed.
 *  - OpenCode's live plugin uses the generated SDK path shape for
 *    `client.session.messages({ path: { id: sessionID } })`, with a narrow
 *    compatibility fallback for older internal clients. Recovery of sessions
 *    that never emitted an idle event lives in the resident's CLI backfill,
 *    not in an unconfirmed plugin API.
 */

export const CAPTURE_HOOK_RELATIVE_PATH = ".oathlock/bin/m9r-capture.mjs";
export const CAPTURE_HOOK_MARKER = "m9r-capture.mjs";
export const OPENCODE_CAPTURE_MARKER = "M9rMemoryPlugin";

/**
 * The actual SessionEnd hook script, written into every repo that connects
 * Claude Code or Codex. Deliberately does almost nothing: read stdin JSON,
 * append one line to the spool, exit -- both providers give this well under
 * two seconds (Codex hard-caps at 3s) and treat the hook as advisory, so
 * anything slower than "append and exit" risks either losing the write
 * entirely or, worse, visibly delaying the human's actual exit from their
 * own session. No dependencies beyond node:fs/node:path -- this must run
 * with a bare `node`, not through this repo's own alias/tsx pipeline, since
 * it executes inside a project that may not even be this one.
 */
export const CAPTURE_HOOK_SCRIPT_SOURCE = `#!/usr/bin/env node
// Generated by \`m9r connect\` -- appends this SessionEnd event to
// .oathlock/capture/pending.jsonl for M9R's resident to drain later.
// Deliberately minimal: no dependencies, no network, one append, exit.
// Never throws into the caller -- Claude Code/Codex treat this hook as
// advisory and non-blocking, but a stack trace on stderr would still be
// a needless surprise in someone's terminal on session exit.
import { appendFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";

const provider = process.argv[2] === "codex" ? "codex" : "claude-code";

function readStdin() {
  return new Promise((resolve) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => { data += chunk; });
    process.stdin.on("end", () => resolve(data));
    process.stdin.on("error", () => resolve(data));
    // Providers that never write to stdin for this event must not hang the hook forever.
    setTimeout(() => resolve(data), 1500).unref();
  });
}

async function main() {
  const raw = await readStdin();
  let payload = {};
  try {
    payload = JSON.parse(raw || "{}");
  } catch {
    return; // malformed input -- nothing safe to record, exit quietly
  }
  const sessionId = payload.session_id;
  const transcriptPath = payload.transcript_path;
  if (!sessionId || !transcriptPath) return;

  const cwd = payload.cwd || process.cwd();
  const job = {
    provider,
    sessionId,
    transcriptPath,
    cwd,
    reason: payload.reason || "other",
    capturedAtIso: new Date().toISOString(),
  };
  const projectRoot = process.env.CLAUDE_PROJECT_DIR || cwd;
  const spoolPath = join(projectRoot, ".oathlock", "capture", "pending.jsonl");
  try {
    await mkdir(dirname(spoolPath), { recursive: true });
    await appendFile(spoolPath, JSON.stringify(job) + "\\n", "utf8");
  } catch {
    /* best-effort -- a failed write here just means this one session isn't captured */
  }
}

main().catch(() => {});
`;

function isRecord(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === "object" && !Array.isArray(value);
}

function parseJsonObject(text: string | null): Record<string, unknown> {
  if (!text) return {};
  try {
    const parsed = JSON.parse(text) as unknown;
    return isRecord(parsed) ? parsed : {};
  } catch {
    return {};
  }
}

/**
 * Merges an M9R SessionEnd hook entry into a Claude-Code-shaped settings
 * file (used for both `.claude/settings.local.json` and, mirrored, for
 * Codex's `.codex/hooks.json`). Additive and idempotent: existing
 * `hooks.SessionEnd` groups are preserved untouched; a group whose command
 * already references our own script is left alone rather than duplicated.
 */
function mergeSessionEndHook(
  existingJsonText: string | null,
  hookCommand: string,
  timeoutSeconds: number,
): { content: string; changed: boolean } {
  const root = parseJsonObject(existingJsonText);
  const hooks = isRecord(root.hooks) ? { ...root.hooks } : {};
  const sessionEndGroups = Array.isArray(hooks.SessionEnd) ? [...(hooks.SessionEnd as unknown[])] : [];

  const alreadyPresent = sessionEndGroups.some((group) => {
    if (!isRecord(group) || !Array.isArray(group.hooks)) return false;
    return group.hooks.some((h) => isRecord(h) && typeof h.command === "string" && h.command.includes(CAPTURE_HOOK_MARKER));
  });
  if (alreadyPresent) {
    return { content: JSON.stringify(root, null, 2) + "\n", changed: false };
  }

  sessionEndGroups.push({
    hooks: [{ type: "command", command: hookCommand, timeout: timeoutSeconds }],
  });
  hooks.SessionEnd = sessionEndGroups;
  const merged = { ...root, hooks };
  return { content: JSON.stringify(merged, null, 2) + "\n", changed: true };
}

/**
 * Inverse of `mergeSessionEndHook`: drops only hook entries whose command references our capture
 * script and leaves every other SessionEnd hook, and every unrelated setting, exactly as found.
 */
export function removeCaptureHook(existingJsonText: string | null): { content: string; changed: boolean } {
  const root = parseJsonObject(existingJsonText);
  if (!isRecord(root.hooks) || !Array.isArray(root.hooks.SessionEnd)) return { content: existingJsonText ?? "", changed: false };
  let changed = false;
  const groups: unknown[] = [];
  for (const group of root.hooks.SessionEnd as unknown[]) {
    if (!isRecord(group) || !Array.isArray(group.hooks)) { groups.push(group); continue; }
    const kept = group.hooks.filter((h) => !(isRecord(h) && typeof h.command === "string" && h.command.includes(CAPTURE_HOOK_MARKER)));
    if (kept.length === group.hooks.length) { groups.push(group); continue; }
    changed = true;
    if (kept.length > 0) groups.push({ ...group, hooks: kept });
  }
  if (!changed) return { content: existingJsonText ?? "", changed: false };
  const hooks: Record<string, unknown> = { ...root.hooks };
  if (groups.length > 0) hooks.SessionEnd = groups; else delete hooks.SessionEnd;
  const next: Record<string, unknown> = { ...root, hooks };
  if (Object.keys(hooks).length === 0) delete next.hooks;
  return { content: JSON.stringify(next, null, 2) + "\n", changed: true };
}

/**
 * `.claude/settings.local.json` — deliberately the gitignored local file,
 * not the committed `.claude/settings.json`. A hook written to the committed
 * file would silently run for every teammate who clones the repo, before
 * they've even seen a trust prompt (project hooks run pre-trust per Claude
 * Code's own permissions docs). Writing to the local file instead makes
 * `m9r connect` itself the per-developer consent, not a repo-wide grant.
 */
export function mergeClaudeCodeLocalSettings(existingJsonText: string | null): { content: string; changed: boolean } {
  return mergeSessionEndHook(
    existingJsonText,
    `node "\${CLAUDE_PROJECT_DIR}/${CAPTURE_HOOK_RELATIVE_PATH}" claude-code`,
    5,
  );
}

/**
 * `.codex/hooks.json` — project-local, real per Codex's own lifecycle-hooks
 * docs. Codex additionally requires an explicit `/hooks` trust review inside
 * the product before a non-managed hook actually runs (a stronger default
 * posture than Claude Code's) -- `m9r connect`'s own output tells the human
 * to do that, this function only writes the definition for them to review.
 */
export function mergeCodexHooks(existingJsonText: string | null): { content: string; changed: boolean } {
  return mergeSessionEndHook(existingJsonText, `node .oathlock/bin/m9r-capture.mjs codex`, 3);
}

/**
 * `.opencode/plugins/m9r-memory.js` — a plain, dependency-free plugin file
 * (OpenCode's own docs ship dependency-free plugin examples the same way).
 * Subscribes to the generic `event` hook rather than a named `session.idle`
 * hook, and handles both `session.idle` (the event OpenCode's own source
 * marks deprecated) and its replacement `session.status` with
 * `status.type === "idle"`, deduped per session id, since which one a given
 * OpenCode version emits isn't something `connect` can detect at write time.
 * Unlike the two hook-based providers, this isn't time-boxed the same way,
 * so it does the transcript fetch itself and spools the finished JSON --
 * the drainer never needs to reach back into a live OpenCode server.
 */
export function buildOpenCodeMemoryPlugin(): string {
  return `// Generated by \`m9r connect\` -- captures this repo's OpenCode sessions into
// M9R's shared memory (.oathlock/capture/pending.jsonl, drained into
// .oathlock/memory/local/opencode/<session-id>.md). Safe to delete; a
// missing plugin just means this repo's OpenCode sessions aren't captured.
//
// The generated SDK path shape is the primary API. A narrow direct-session
// compatibility fallback keeps older OpenCode clients working. If a future
// OpenCode version changes both shapes, this plugin fails closed (logs to
// app.log, never throws into the host process) rather than spooling malformed
// data.
import { appendFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";

const seen = new Set();
const inFlight = new Set();
const emptyRetryScheduled = new Set();

export const M9rMemoryPlugin = async ({ client, directory, project }) => {
  async function captureIdleSession(sessionID) {
    if (!sessionID || seen.has(sessionID) || inFlight.has(sessionID)) return;
    inFlight.add(sessionID);
    try {
      // OpenCode's plugin client uses the generated SDK path shape. Keep the
      // older direct-session shape as a compatibility fallback for versions
      // that exposed the internal client instead.
      let result = await client.session.messages({ path: { id: sessionID } });
      let messages = Array.isArray(result?.data) ? result.data : Array.isArray(result) ? result : null;
      if (messages === null) {
        result = await client.session.messages({ sessionID });
        messages = Array.isArray(result?.data) ? result.data : Array.isArray(result) ? result : [];
      }
      // OpenCode can emit an idle event when a session is first created, before
      // its first user message exists. Do not consume that event permanently:
      // the completed prompt will emit another idle/status event with content.
      // Empty sessions have no memory value, and a failed spool write must be
      // retried on the next lifecycle event rather than being marked captured.
      if (messages.length === 0) {
        // The initial idle event can race session creation. Give that
        // creation one short, bounded retry window so a later lifecycle event
        // cannot be lost behind the in-flight request.
        if (!emptyRetryScheduled.has(sessionID)) {
          emptyRetryScheduled.add(sessionID);
          const timer = setTimeout(() => {
            emptyRetryScheduled.delete(sessionID);
            void captureIdleSession(sessionID);
          }, 100);
          timer.unref?.();
        }
        return;
      }
      const root = directory || project?.worktree || process.cwd();
      const spoolPath = join(root, ".oathlock", "capture", "pending.jsonl");
      const job = {
        provider: "opencode",
        sessionId: sessionID,
        cwd: root,
        capturedAtIso: new Date().toISOString(),
        export: { messages },
      };
      await mkdir(dirname(spoolPath), { recursive: true });
      await appendFile(spoolPath, JSON.stringify(job) + "\\n", "utf8");
      seen.add(sessionID);
    } catch (error) {
      try {
        await client.app.log({ service: "m9r-memory", level: "error", message: String(error?.message || error) });
      } catch {
        /* logging is best-effort; never let capture failures surface to the user */
      }
    } finally {
      inFlight.delete(sessionID);
    }
  }

  return {
    event: async ({ event }) => {
      if (event?.type === "session.idle" && event.properties?.sessionID) {
        // Never hold OpenCode's event dispatcher open while asking its API for
        // messages. The first idle event can occur inside session creation;
        // awaiting here deadlocks POST /session on a fresh server.
        void captureIdleSession(event.properties.sessionID);
      } else if (event?.type === "session.status") {
        // OpenCode has emitted both shapes over its supported plugin API:
        // { sessionID, status } and { info: { sessionID, status } }.
        // Older builds used info.id. Accept all three so a completed turn
        // cannot be mistaken for an unrelated status event or dropped.
        const properties = event.properties || {};
        const info = properties.info || {};
        const status = info.status || properties.status;
        if (status?.type !== "idle") return;
        void captureIdleSession(properties.sessionID || info.sessionID || info.id || properties.part?.sessionID);
      }
    },
  };
};
`;
}
