/**
 * Registers `oathlock terminal runtime` to launch at user logon, so the
 * Mission ACP Bridge (and the resident supervisor it launches) survive a
 * reboot without anyone opening a terminal.
 *
 * Deliberately the HKCU Run registry key, not a Scheduled Task: on real
 * hardware (not just a locked-down policy), `schtasks /create /sc onlogon`
 * was denied by this machine's security stack even at /rl limited, while
 * plain /sc once and /sc daily tasks created fine -- onlogon specifically
 * is a well-known malware-persistence trigger and gets flagged/blocked by
 * AV/EDR behavior monitoring independent of admin rights. HKCU\...\Run is
 * the mechanism every mainstream consumer app (Discord, Slack, Spotify)
 * already uses for "start with Windows," needs no elevation, and wrote
 * clean in the same environment where the Scheduled Task was denied.
 *
 * A small PowerShell launch script still does the hiding: a Run-key value
 * that points straight at node.exe would flash a console window on every
 * login, so the value instead points at `powershell -WindowStyle Hidden
 * -File <script>`, and the script itself does `Start-Process ...
 * -WindowStyle Hidden`.
 */

export const WINDOWS_RUN_KEY_PATH = "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run";
export const WINDOWS_RUN_KEY_VALUE_NAME = "OathLockRuntime";

export interface WindowsLaunchScriptInput {
  nodeExecutable: string;
  /**
   * Flags for `node` itself, before the entry path -- e.g. `--import
   * .../register-alias.mjs` when running from raw .ts source (a monorepo
   * dev checkout), which resolves the `@/lib/...` path aliases every other
   * invocation of this CLI already relies on. A packaged/compiled entry
   * needs none of this. Omitting it isn't a smaller launcher, it's a
   * launcher that silently fails to boot at all -- Node cannot execute a
   * bare .ts file, and there's no console for the failure to appear in.
   */
  nodeArgs: string[];
  cliEntryPath: string;
  args: string[];
  workingDirectory: string;
  /**
   * Environment variables the launched process needs that the login
   * environment won't otherwise carry -- e.g. OATHLOCK_TERMINAL_PANES.
   * Start-Process has no -Environment parameter, so these are set as
   * $env: assignments in the wrapper script's own process, which
   * Start-Process's child then inherits. Optional and empty by default;
   * omitting it changes nothing about existing installs.
   */
  envVars?: Record<string, string>;
}

function psQuote(value: string): string {
  // Single-quoted PowerShell literal: only a literal single quote needs escaping (doubled).
  return `'${value.replace(/'/g, "''")}'`;
}

export function buildWindowsLaunchScript(input: WindowsLaunchScriptInput): string {
  const argList = [...input.nodeArgs, input.cliEntryPath, ...input.args].map(psQuote).join(", ");
  const envLines = Object.entries(input.envVars ?? {}).map(([key, value]) => `$env:${key} = ${psQuote(value)}`);
  return [
    "# Generated by `oathlock service install` -- safe to delete; re-run the",
    "# command to recreate it. Launches the M9R runtime hidden so the",
    "# logon launch never flashes a console window.",
    "#",
    "# Best-effort mitigation, not a guarantee: a process started via the Run",
    "# key fires very early in logon, sometimes before the interactive desktop",
    "# session has fully stabilized. A long-running child of that process can",
    "# later fail to spawn ITS OWN subprocesses (observed: agent CLIs failing",
    "# with CreateProcessAsUserW 1312, \"a specified logon session does not",
    "# exist or may have terminated\") -- this is Windows tearing down an early,",
    "# transient logon-session token once the real one is established. Waiting",
    "# for explorer.exe (the interactive shell) to be running, plus a fixed",
    "# margin, is the standard mitigation for exactly this class of early-",
    "# Run-key timing issue. This does not fix a token invalidated later by an",
    "# unrelated Windows session event (e.g. lock/unlock) -- that is what the",
    "# prompt timeout in acp-stdio-adapter.ts exists to recover from instead.",
    "$deadline = (Get-Date).AddSeconds(60)",
    "while (-not (Get-Process -Name explorer -ErrorAction SilentlyContinue) -and (Get-Date) -lt $deadline) {",
    "  Start-Sleep -Seconds 2",
    "}",
    "Start-Sleep -Seconds 10",
    ...envLines,
    `Start-Process -FilePath ${psQuote(input.nodeExecutable)} -ArgumentList @(${argList}) -WorkingDirectory ${psQuote(input.workingDirectory)} -WindowStyle Hidden`,
    "",
  ].join("\r\n");
}

export function buildHiddenLaunchCommand(scriptPath: string): string {
  return `powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "${scriptPath}"`;
}

export function buildRegAddArgs(scriptPath: string): string[] {
  return ["add", WINDOWS_RUN_KEY_PATH, "/v", WINDOWS_RUN_KEY_VALUE_NAME, "/t", "REG_SZ", "/d", buildHiddenLaunchCommand(scriptPath), "/f"];
}

export function buildRegDeleteArgs(): string[] {
  return ["delete", WINDOWS_RUN_KEY_PATH, "/v", WINDOWS_RUN_KEY_VALUE_NAME, "/f"];
}

export function buildRegQueryArgs(): string[] {
  return ["query", WINDOWS_RUN_KEY_PATH, "/v", WINDOWS_RUN_KEY_VALUE_NAME];
}
