/**
 * Rules File Generator — M9R v5
 * ----------------------------------------------------------------------------
 * Turns de-duplicated GeneratedRules into the artifacts a user actually drops
 * into their workflow:
 *   - AGENTS.md                  (generic agent rules file)
 *   - CLAUDE.md                  (Claude Code project memory)
 *   - .cursor/rules/oathlock.mdc (Cursor project rule, with frontmatter)
 *   - plain copy/paste block     (paste at the top of any prompt)
 *
 * Every file is evidence-only by construction: it states its source/provenance
 * and carries only the rules M9R actually generated from observed session
 * behavior. It never injects static, generic guardrails (verification, metadata,
 * or command-failure protocols) — exporting prompt-junk that wasn't backed by
 * evidence is exactly what M9R exists to prevent.
 *
 * Pure module (no DOM/IO).
 */

import type { GeneratedRule, RuleType } from "@/lib/generated-rules";
import { RULE_TYPE_LABELS } from "@/lib/generated-rules";

export type RulesFileFormat = "agents" | "claude" | "cursor" | "plain";

export interface RulesFileMeta {
  /** Source session name or id, when known (report-local exports). */
  sessionName?: string | null;
  /** Workspace name, for workspace-scoped exports. */
  workspaceName?: string | null;
  /**
   * Export context. "session" → report-local rules from a single run.
   * "workspace" → the active persisted workspace ruleset. Controls titles,
   * grouping, and what counts as exportable. Defaults to "session".
   */
  scope?: "session" | "workspace";
  /** Include needs-review rules in addition to active ones. Default false. */
  includeNeedsReview?: boolean;
  /** Override the generated date (defaults to today). Mostly for tests. */
  date?: string;
}

export interface RulesFile {
  format: RulesFileFormat;
  /** Suggested filename, e.g. "AGENTS.md" or ".cursor/rules/oathlock.mdc". */
  filename: string;
  /** Full file contents. */
  content: string;
}

const PURPOSE =
  "Generated by M9R from observed session behavior. Keep only rules backed by evidence — apply them, then re-analyze a later session to see whether they helped.";

// --- Partitioning -----------------------------------------------------------

function partition(rules: GeneratedRule[]) {
  const active = rules.filter((r) => r.status === "active");
  const review = rules.filter((r) => r.status === "needs_review");
  const lowOrRetired = rules.filter((r) => r.status === "low_confidence" || r.status === "retired");
  return { active, review, lowOrRetired };
}

function today(meta?: RulesFileMeta): string {
  return meta?.date ?? new Date().toISOString().slice(0, 10);
}

function sourceLine(meta?: RulesFileMeta): string {
  return meta?.sessionName ? `Source session: ${meta.sessionName}` : "Source session: (not named)";
}

// --- Markdown body (shared by AGENTS.md / CLAUDE.md) ------------------------

function ruleBullet(rule: GeneratedRule): string {
  // One enforceable line plus a quiet evidence/confidence note.
  const note = `_(${RULE_TYPE_LABELS[rule.ruleType]} · ${rule.confidence} confidence · ${rule.expectedPrevention})_`;
  return `- ${rule.body}\n  ${note}`;
}

function markdownBody(title: string, rules: GeneratedRule[], meta?: RulesFileMeta): string {
  const { active, review, lowOrRetired } = partition(rules);
  const lines: string[] = [];

  lines.push(`# ${title}`);
  lines.push("");
  lines.push(`> Generated by M9R on ${today(meta)}. ${sourceLine(meta)}.`);
  lines.push("");
  lines.push(PURPOSE);
  lines.push("");

  lines.push("## Highest-priority rules");
  lines.push("");
  if (active.length === 0) {
    lines.push("_No high-confidence rules yet — analyze a messier session to generate some._");
  } else {
    for (const rule of active) lines.push(ruleBullet(rule));
  }
  lines.push("");

  if (review.length > 0) {
    lines.push("## Needs review (conflicting or unverified)");
    lines.push("");
    for (const rule of review) lines.push(ruleBullet(rule));
    lines.push("");
  }

  if (lowOrRetired.length > 0) {
    lines.push("## Low-confidence / retired (do not enforce yet)");
    lines.push("");
    for (const rule of lowOrRetired) lines.push(ruleBullet(rule));
    lines.push("");
  }

  return lines.join("\n");
}

// --- Cursor .mdc (frontmatter + markdown) -----------------------------------

function cursorBody(rules: GeneratedRule[], meta?: RulesFileMeta): string {
  const { active, review, lowOrRetired } = partition(rules);
  const lines: string[] = [];

  // Cursor rule frontmatter: applied broadly, always attached.
  lines.push("---");
  lines.push("description: M9R-generated rules from an observed coding-agent session");
  lines.push("globs:");
  lines.push("alwaysApply: true");
  lines.push("---");
  lines.push("");
  lines.push(`# M9R Rules (generated ${today(meta)})`);
  lines.push("");
  lines.push(`${PURPOSE} ${sourceLine(meta)}.`);
  lines.push("");
  lines.push("## Rules");
  lines.push("");
  if (active.length === 0) {
    lines.push("- (no high-confidence rules yet)");
  } else {
    for (const rule of active) lines.push(`- ${rule.body}`);
  }
  lines.push("");
  if (review.length > 0 || lowOrRetired.length > 0) {
    lines.push("## Not enforced (needs review / low confidence)");
    lines.push("");
    for (const rule of [...review, ...lowOrRetired]) lines.push(`- ${rule.body}`);
    lines.push("");
  }
  return lines.join("\n");
}

// --- Plain copy/paste block -------------------------------------------------

function plainBody(rules: GeneratedRule[], meta?: RulesFileMeta): string {
  const { active, lowOrRetired, review } = partition(rules);
  const lines: string[] = [];
  lines.push("=== OATHLOCK RULES (HIGHEST PRIORITY) ===");
  lines.push(`# generated ${today(meta)} · ${sourceLine(meta)}`);
  lines.push("");
  if (active.length === 0) {
    lines.push("* (no high-confidence rules yet)");
  } else {
    for (const rule of active) lines.push(`* ${rule.body}`);
  }
  if (review.length > 0 || lowOrRetired.length > 0) {
    lines.push("");
    lines.push("# Not enforced yet (review / low confidence)");
    for (const rule of [...review, ...lowOrRetired]) lines.push(`* ${rule.body}`);
  }
  lines.push("");
  lines.push("=== END OATHLOCK RULES ===");
  return lines.join("\n");
}

// --- Workspace-scoped exports -----------------------------------------------

const WORKSPACE_PURPOSE =
  "These are the active instructions M9R recommends carrying into future AI coding-agent runs, promoted from observed sessions. Retired and needs-review rules are excluded by default.";

/** Rules eligible for a workspace export: active, plus needs-review when asked. */
function exportableWorkspaceRules(rules: GeneratedRule[], meta?: RulesFileMeta): GeneratedRule[] {
  return rules.filter(
    (r) => r.status === "active" || (meta?.includeNeedsReview && r.status === "needs_review"),
  );
}

function workspaceHeaderLine(meta?: RulesFileMeta): string {
  const name = meta?.workspaceName?.trim() || "(unnamed workspace)";
  return `> M9R Workspace Rules · workspace: ${name} · generated ${today(meta)}.`;
}

/** Group rules by rule type, preserving first-seen order of the types. */
function groupByType(rules: GeneratedRule[]): Array<[string, GeneratedRule[]]> {
  const groups = new Map<string, GeneratedRule[]>();
  for (const r of rules) {
    const list = groups.get(r.ruleType) ?? [];
    list.push(r);
    groups.set(r.ruleType, list);
  }
  return [...groups.entries()];
}

function workspaceMarkdownBody(title: string, rules: GeneratedRule[], meta?: RulesFileMeta): string {
  const active = exportableWorkspaceRules(rules, meta);
  const lines: string[] = [];

  lines.push(`# ${title}`);
  lines.push("");
  lines.push(workspaceHeaderLine(meta));
  lines.push("");
  lines.push(WORKSPACE_PURPOSE);
  lines.push("");
  lines.push(`**${active.length} active rule${active.length === 1 ? "" : "s"}.**`);
  lines.push("");

  if (active.length === 0) {
    lines.push("_No active workspace rules yet. Promote rules from a Blackbox Report to populate this._");
    lines.push("");
  } else {
    for (const [type, group] of groupByType(active)) {
      lines.push(`## ${RULE_TYPE_LABELS[type as RuleType] ?? type}`);
      lines.push("");
      for (const rule of group) lines.push(ruleBullet(rule));
      lines.push("");
    }
  }

  return lines.join("\n");
}

function workspaceCursorBody(rules: GeneratedRule[], meta?: RulesFileMeta): string {
  const active = exportableWorkspaceRules(rules, meta);
  const lines: string[] = [];
  lines.push("---");
  lines.push("description: M9R workspace rules — active instructions for AI coding-agent runs");
  lines.push("globs:");
  lines.push("alwaysApply: true");
  lines.push("---");
  lines.push("");
  lines.push(`# M9R Workspace Rules (generated ${today(meta)})`);
  lines.push("");
  lines.push(WORKSPACE_PURPOSE);
  lines.push("");
  if (active.length === 0) {
    lines.push("- (no active workspace rules yet)");
  } else {
    for (const [type, group] of groupByType(active)) {
      lines.push(`## ${RULE_TYPE_LABELS[type as RuleType] ?? type}`);
      for (const rule of group) lines.push(`- ${rule.body}`);
      lines.push("");
    }
  }
  return lines.join("\n");
}

function workspacePlainBody(rules: GeneratedRule[], meta?: RulesFileMeta): string {
  const active = exportableWorkspaceRules(rules, meta);
  const lines: string[] = [];
  lines.push("=== OATHLOCK WORKSPACE RULES ===");
  lines.push(`# ${active.length} active rule(s) · generated ${today(meta)}`);
  lines.push("");
  if (active.length === 0) {
    lines.push("* (no active workspace rules yet)");
  } else {
    for (const rule of active) lines.push(`* ${rule.body}`);
  }
  lines.push("");
  lines.push("=== END OATHLOCK WORKSPACE RULES ===");
  return lines.join("\n");
}

// --- Public API -------------------------------------------------------------

/**
 * Generate a single rules artifact in the requested format. The export context
 * (meta.scope) selects report-local titling ("M9R Rules From This Session")
 * vs workspace titling ("M9R Workspace Rules", grouped, active-only).
 */
export function generateRulesFile(
  format: RulesFileFormat,
  rules: GeneratedRule[],
  meta?: RulesFileMeta,
): RulesFile {
  const workspace = meta?.scope === "workspace";

  if (workspace) {
    switch (format) {
      case "agents":
        return { format, filename: "AGENTS.md", content: workspaceMarkdownBody("M9R Workspace Rules", rules, meta) };
      case "claude":
        return { format, filename: "CLAUDE.md", content: workspaceMarkdownBody("M9R Workspace Rules", rules, meta) };
      case "cursor":
        return { format, filename: ".cursor/rules/oathlock.mdc", content: workspaceCursorBody(rules, meta) };
      case "plain":
        return { format, filename: "oathlock-workspace-rules.txt", content: workspacePlainBody(rules, meta) };
    }
  }

  switch (format) {
    case "agents":
      return { format, filename: "AGENTS.md", content: markdownBody("M9R Rules From This Session", rules, meta) };
    case "claude":
      return { format, filename: "CLAUDE.md", content: markdownBody("M9R Rules From This Session", rules, meta) };
    case "cursor":
      return { format, filename: ".cursor/rules/oathlock.mdc", content: cursorBody(rules, meta) };
    case "plain":
      return { format, filename: "oathlock-rules.txt", content: plainBody(rules, meta) };
  }
}

/** Convenience: generate all four formats at once. */
export function generateAllRulesFiles(rules: GeneratedRule[], meta?: RulesFileMeta): RulesFile[] {
  return (["agents", "claude", "cursor", "plain"] as RulesFileFormat[]).map((f) =>
    generateRulesFile(f, rules, meta),
  );
}
