import type { Metadata } from "next";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { CONTACT_EMAIL, CONTACT_MAILTO } from "@/lib/contact";

export const metadata: Metadata = { title: "Terms of Service — M9R", description: "Terms governing M9R accounts and controlled AI-agent workflows." };

const clauses = [
  ["Service", "M9R helps teams connect coding agents, load workspace rules, coordinate controlled runs, prepare evidence for human review, and retain review records. M9R is not a code reviewer, security guarantee, legal adviser, or substitute for human oversight."],
  ["Accounts and usernames", "You must provide accurate account information, safeguard credentials, and promptly report unauthorized access. Usernames are public workspace handles and must not impersonate others, violate rights, mislead users, or contain abusive content. We may rename or reserve a username when reasonably necessary."],
  ["Eligibility", "You must be at least 18 years old and legally able to enter this agreement. The service is not directed to children."],
  ["Your content and authority", "You retain ownership of content you submit. You grant M9R the limited rights needed to host, process, transmit, redact, and display that content to provide and secure the service. You represent that you have authority to connect each repository, agent, provider, and workspace and to submit the data involved."],
  ["AI agents and human responsibility", "AI agents can make incorrect, unsafe, incomplete, or unexpected changes. Rules, preflight checks, evidence drafts, approvals, passports, and efficiency measurements reduce ambiguity but do not guarantee correctness. You remain responsible for reviewing changes, protecting production systems, maintaining backups, and deciding whether to approve, adopt, deploy, or rely on agent work."],
  ["Sensitive data", "Do not submit passwords, API keys, private keys, payment-card data, protected health information, government identifiers, or other highly sensitive or regulated data unless M9R has expressly agreed in writing to support that data and any required agreement is in place. Use available redaction controls and least-privilege connections."],
  ["Acceptable use", "You may not break laws; infringe rights; distribute malware; probe or attack systems without authorization; bypass access, rate, billing, or security controls; scrape or overload the service; share accounts improperly; or use M9R to harm people or systems. Security research requires prior written authorization."],
  ["Service changes and suspension", "We may change, limit, suspend, or discontinue features and may suspend access to protect users, the service, or third parties; address abuse; comply with law; or respond to nonpayment. Where practical, we will provide notice."],
  ["No warranty", "THE SERVICE IS PROVIDED AS IS AND AS AVAILABLE. TO THE MAXIMUM EXTENT PERMITTED BY LAW, M9R DISCLAIMS IMPLIED WARRANTIES, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. WE DO NOT WARRANT UNINTERRUPTED SERVICE OR COMPLETE, ACCURATE, OR SECURE RESULTS."],
  ["Liability", "TO THE MAXIMUM EXTENT PERMITTED BY LAW, M9R WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR LOST PROFITS, REVENUE, DATA, GOODWILL, OR BUSINESS. M9R'S AGGREGATE LIABILITY ARISING FROM THE SERVICE WILL NOT EXCEED THE GREATER OF US$100 OR THE AMOUNT YOU PAID M9R IN THE 12 MONTHS BEFORE THE EVENT GIVING RISE TO THE CLAIM. Some jurisdictions do not allow certain exclusions, so they may not apply to you."],
  ["Termination and survival", "You may stop using the service and request account deletion. We may terminate for material breach. Provisions that by nature should survive—including ownership, disclaimers, liability limits, and dispute terms—survive termination."],
  ["Changes and contact", "We may update these Terms and will post the effective date. Material changes may receive additional notice where required. Continued use after the effective date means acceptance, except where law requires another form of consent."],
] as const;

export default function TermsPage() {
  return <div className="lp lp-page"><div className="lp-atmos" aria-hidden /><Nav /><main className="lp-page-main lp-page-main--narrow"><header className="lp-page-head"><div className="lp-ph-eyebrow lp-ph-eyebrow--steel"><span className="lp-tick" aria-hidden />Legal record</div><h1 className="lp-h-page">Terms of service</h1><p className="lp-updated">Effective · July 15, 2026</p></header><div className="lp-letter" style={{ paddingBottom: 72 }}><section className="lp-clause"><div className="lp-clause-no">Important</div><h2>Operator and governing-law details</h2><p>M9R&apos;s legal operator, business address, and governing jurisdiction must be supplied before general commercial launch. Until then, contact <a href={CONTACT_MAILTO}>{CONTACT_EMAIL}</a>. This notice does not create a governing-law term.</p></section>{clauses.map(([title, body], index) => <section key={title} className="lp-clause"><div className="lp-clause-no">§ {String(index + 1).padStart(2, "0")}</div><h2>{title}</h2><p className={title === "No warranty" || title === "Liability" ? "lp-legalese" : undefined}>{body}</p></section>)}</div></main><Footer /></div>;
}
