/**
 * OathLock v5 acceptance loop — proves the repeatable core works end to end and
 * stays honest: messy session → report → ≥3 specific rules → dedupe → all export
 * formats → follow-up session → before/after comparison.
 */

import test from "node:test";
import assert from "node:assert/strict";
import { parseRawOutput } from "../src/lib/raw-trace-parser.ts";
import { normalizeToTrace } from "../src/lib/normalize-trace.ts";
import { computeTraceMetrics } from "../src/lib/trace-metrics.ts";
import { generateBlackboxReport } from "../src/lib/blackbox-report.ts";
import { generateRulesFromReport } from "../src/lib/generated-rules.ts";
import { dedupeRules } from "../src/lib/rule-deduplication.ts";
import { generateAllRulesFiles, generateRulesFile } from "../src/lib/rules-file-generator.ts";
import { summarizeRun, compareRuns } from "../src/lib/run-comparison.ts";

const MESSY = `## User
Make the auth tests pass.
## Assistant
⏺ Read(src/lib/auth.ts)
⏺ Bash(npm test)
  ⎿  Error: 2 tests failed
⏺ Edit(src/lib/auth.ts)
⏺ Bash(npm test)
  ⎿  Error: 1 test failed
⏺ Read(src/lib/auth.ts)
⏺ Edit(src/lib/auth.ts)
⏺ Edit(src/lib/auth.ts)
⏺ Bash(npm test)
  ⎿  Error: still failing
`;

const FOLLOWUP = `## User
Make the auth tests pass.
## Assistant
⏺ Read(src/lib/auth.ts)
⏺ Edit(src/lib/auth.ts)
⏺ Bash(npm test)
  ⎿  All tests passed
`;

function analyze(raw: string) {
  const trace = normalizeToTrace(parseRawOutput(raw).trace);
  return { trace, metrics: computeTraceMetrics(trace) };
}

test("messy session generates at least 3 specific, evidence-backed rules", async () => {
  const { trace, metrics } = analyze(MESSY);
  const report = await generateBlackboxReport(trace);
  const rules = dedupeRules(generateRulesFromReport(report, metrics)).rules;

  assert.ok(rules.length >= 3, `expected >=3 rules, got ${rules.length}`);
  // Every rule must be behavioral + evidence-backed, never vague.
  for (const rule of rules) {
    assert.ok(rule.body.length > 30, "rule body should be specific");
    assert.ok(rule.evidenceSummary.length > 0, "rule needs an evidence summary");
    assert.ok(!/be careful|write clean code|best practices/i.test(rule.body), `vague rule: ${rule.body}`);
  }
  // The core behaviors should be present.
  const types = rules.map((r) => r.ruleType);
  assert.ok(types.includes("retry_prevention"));
  assert.ok(types.includes("edit_thrash_prevention"));
  assert.ok(types.includes("verification"));
});

test("dedupe collapses duplicate rules of the same behavior", () => {
  const base = {
    title: "t",
    body: "After a command fails twice, do not rerun it unless inputs changed.",
    ruleType: "retry_prevention" as const,
    confidence: "high" as const,
    evidenceSummary: "x",
    sourceFindingId: "f1",
    expectedPrevention: "p",
    createdAt: "2026-01-01",
    status: "active" as const,
  };
  const dupes = [
    { ...base, id: "a" },
    { ...base, id: "b", confidence: "low" as const },
  ];
  const { rules, mergedCount } = dedupeRules(dupes);
  assert.equal(rules.length, 1, "identical behavior should collapse to one");
  assert.equal(mergedCount, 1);
  assert.equal(rules[0].confidence, "high", "should keep the higher-confidence rule");
});

test("all four export formats are produced with required sections", async () => {
  const { trace, metrics } = analyze(MESSY);
  const report = await generateBlackboxReport(trace);
  const rules = dedupeRules(generateRulesFromReport(report, metrics)).rules;

  const files = generateAllRulesFiles(rules, { sessionName: "auth-session", date: "2026-06-27" });
  const byName = Object.fromEntries(files.map((f) => [f.filename, f.content]));

  assert.ok(byName["AGENTS.md"]);
  assert.ok(byName["CLAUDE.md"]);
  assert.ok(byName[".cursor/rules/oathlock.mdc"]);
  assert.ok(files.some((f) => f.format === "plain"));

  // AGENTS.md must carry provenance and the generated rules — and nothing else.
  const agents = byName["AGENTS.md"];
  assert.match(agents, /Generated by M9R/);
  assert.match(agents, /Source session: auth-session/);
  assert.match(agents, /Highest-priority rules/);

  // Exports are evidence-only: no static, generic guardrail boilerplate.
  const BANNED_SCAFFOLD = [
    /Verification protocol/i,
    /## Verification/,
    /Before reporting a task as done/i,
    /If a command fails/i,
    /If usage metadata/i,
    /Keep these rules honest/i,
  ];
  for (const file of files) {
    for (const re of BANNED_SCAFFOLD) {
      assert.ok(!re.test(file.content), `${file.filename} must not contain ${re}`);
    }
  }

  // Cursor file must have frontmatter.
  assert.match(byName[".cursor/rules/oathlock.mdc"], /^---\n[\s\S]*alwaysApply: true/);

  // Plain block must be wrapped.
  const plain = generateRulesFile("plain", rules).content;
  assert.match(plain, /=== OATHLOCK RULES \(HIGHEST PRIORITY\) ===/);
  for (const re of BANNED_SCAFFOLD) {
    assert.ok(!re.test(plain), `plain block must not contain ${re}`);
  }
});

test("before/after comparison reports improvement conservatively", async () => {
  const before = analyze(MESSY);
  const after = analyze(FOLLOWUP);

  const cmp = compareRuns(summarizeRun(before.trace, before.metrics), summarizeRun(after.trace, after.metrics));

  // The follow-up has fewer failures/edits → should read as improved, but the
  // summary must NOT claim causation.
  assert.equal(cmp.verdict, "improved");
  assert.match(cmp.summary, /not proof that a rule changed the outcome/i);
  const retries = cmp.metrics.find((m) => m.key === "retries");
  assert.ok(retries);
});

test("comparison returns insufficient_data for featureless runs", () => {
  const empty = { trace: normalizeToTrace({ steps: [] }), metrics: computeTraceMetrics(normalizeToTrace({ steps: [] })) };
  const cmp = compareRuns(summarizeRun(empty.trace, empty.metrics), summarizeRun(empty.trace, empty.metrics));
  assert.equal(cmp.verdict, "insufficient_data");
});

test("cost is never compared when metadata is absent", async () => {
  const before = analyze(MESSY);
  const after = analyze(FOLLOWUP);
  const cmp = compareRuns(summarizeRun(before.trace, before.metrics), summarizeRun(after.trace, after.metrics));
  assert.equal(cmp.costComparable, false);
  assert.ok(!cmp.metrics.some((m) => m.key === "costUsd"), "no cost row without metadata");
});
