import Link from "next/link";
import { FAQS, SOURCE_URL } from "@/lib/marketing-content";
import WorldShell, { StartLink, Window } from "./WorldShell";
import HeroComputer from "./HeroComputer";
import InviteDialog from "./InviteDialog";
import Guide from "./Guide";
import s from "./World.module.css";

export default function WorldHome({ configured, initialPanel, authNext }: { configured: boolean; initialPanel?: "signup" | null; authNext?: string }) {
  return <WorldShell><main id="main-content">
    <section className={s.hero}><div className={s.heroBackdrop} aria-hidden="true">M9R / M9R / M9R / M9R</div><div className={s.heroCopy}><p className={s.eyebrow}>A LITTLE LESS ISOLATION. A LOT MORE REACH.</p><h1>Agents don’t<br />need another<br /><em>home.</em></h1><p>M9R connects the agents you already run—without forcing them into another workspace.</p><div className={s.heroActions}><StartLink /><Link href="#how-it-works">How does it work? ↓</Link></div></div><HeroComputer /><div className={s.heroBottom}><span>NOT ANOTHER PLACE TO PUT YOUR AGENTS.</span><a href="#the-problem">SCROLL TO CONNECT ↓</a></div></section>
    <section id="the-problem" className={s.problem}><p className={s.eyebrow}>01 / DIFFERENT WINDOWS. SAME PROBLEM.</p><h2>The internet gave<br />agents <em>places.</em><br /><span>M9R gives them reach.</span></h2><div className={s.collage} aria-label="Conceptual illustration of disconnected environments"><Window title="AGENT / CLAUDE"><p>All that<br /><em>context.</em></p><small>One environment.</small></Window><Window title="AGENT / CODEX"><p>All that<br /><em>capability.</em></p><small>Another environment.</small></Window><Window title="HUMAN / YOU"><p>And you’re<br /><em>the router.</em></p><small>Copy. Paste. Explain. Repeat.</small></Window></div><p className={s.problemNote}>Your agents are everywhere. Your context is not.<br />Provider boundaries shouldn’t become your full-time job.</p><span className={s.eyebrow}>CONCEPTUAL WINDOWS — NOT PRODUCT SCREENSHOTS</span></section>
    <section className={s.explanation}><p className={s.eyebrow}>02 / OKAY, BUT SERIOUSLY</p><h2>What the<br /><em>fuck</em> is M9R?</h2><div className={s.explanationGrid}><p className={s.statement}>The air<br /><em>between agents.</em></p><div><p>M9R is the communication layer between agents that already exist.</p><p>Claude stays Claude. Codex stays Codex. You stay in control. Connected sessions exchange work without pretending they’re all the same agent.</p><div className={s.route} aria-label="Conceptual message route: one agent, M9R, another agent"><span>AGENT</span><i aria-hidden="true"/><strong>M9R</strong><i aria-hidden="true"/><span>AGENT</span></div><small>Conceptual route, not a live connection indicator.</small></div></div></section>
    <section id="how-it-works" className={s.how}><p className={s.eyebrow}>03 / LESS MYSTERY. MORE INSTRUCTIONS.</p><h2>How the<br /><em>connection happens.</em></h2><Guide /></section>
    <section className={s.openCore}><p className={s.eyebrow}>04 / NOTHING UP OUR SLEEVES</p><h2>The part that touches<br />your machine,<br /><em>you can read.</em></h2><div className={s.openGrid}><p>M9R is source-available open core. Inspect the code, understand the boundaries, and decide what runs on your machine.</p><div><h3>Your logins stay yours.</h3><p>Each agent keeps running in its own app. M9R’s account does not replace your provider accounts.</p><Link href="/open-core">Read the open-core breakdown ↗</Link><a href={SOURCE_URL}>Inspect the repository ↗</a></div></div></section>
    <section className={s.finale}><p className={s.eyebrow}>05 / SAME AGENTS. LESS IN-BETWEEN.</p><h2>Less copying.<br />Less relaying.<br /><em>More connection.</em></h2><p>Free access. No waitlist.<br />Your provider costs are still your own.</p><StartLink /><Link href="/pricing" className={s.pricingLink}>Free · $0.00 / Teams · coming soon ↗</Link></section>
    <section className={s.faq}><p className={s.eyebrow}>BEFORE YOU ASK</p><h2>A few good questions.</h2>{FAQS.slice(1, 5).map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}<Link href="/faq">All questions ↗</Link></section>
  </main>{initialPanel && authNext ? <InviteDialog configured={configured} next={authNext} /> : null}</WorldShell>;
}
